CREATE TYPE "public"."bucket_granularity" AS ENUM('minute', 'hour', 'day');--> statement-breakpoint
CREATE TABLE "aggregation_batches" (
	"batch_id" varchar(64) PRIMARY KEY NOT NULL,
	"project_id" uuid NOT NULL,
	"applied_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dirty_buckets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dirty_buckets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"metric_id" uuid NOT NULL,
	"metric_version" integer NOT NULL,
	"day_start" timestamp (3) with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "metric_buckets" (
	"metric_id" uuid NOT NULL,
	"metric_version" integer NOT NULL,
	"granularity" "bucket_granularity" NOT NULL,
	"bucket_start" timestamp (3) with time zone NOT NULL,
	"series_key" varchar(128) NOT NULL,
	"dim_name" varchar(128) DEFAULT '$total' NOT NULL,
	"dim_value" varchar(256) DEFAULT '$total' NOT NULL,
	"count" bigint DEFAULT 0 NOT NULL,
	"sum" double precision DEFAULT 0 NOT NULL,
	"min" double precision,
	"max" double precision,
	"value" double precision,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "metric_buckets_metric_id_metric_version_granularity_bucket_start_series_key_dim_name_dim_value_pk" PRIMARY KEY("metric_id","metric_version","granularity","bucket_start","series_key","dim_name","dim_value")
);
--> statement-breakpoint
CREATE TABLE "metric_dimension_values" (
	"metric_id" uuid NOT NULL,
	"metric_version" integer NOT NULL,
	"dim_name" varchar(128) NOT NULL,
	"dim_value" varchar(256) NOT NULL,
	"first_seen_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "metric_dimension_values_metric_id_metric_version_dim_name_dim_value_pk" PRIMARY KEY("metric_id","metric_version","dim_name","dim_value")
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" uuid PRIMARY KEY NOT NULL,
	"project_id" uuid NOT NULL,
	"name" varchar(255) NOT NULL,
	"timestamp" timestamp (3) with time zone NOT NULL,
	"properties" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ingested_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "failed_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"queue" varchar(128) NOT NULL,
	"job_id" varchar(255),
	"payload" jsonb NOT NULL,
	"error" text NOT NULL,
	"attempts_made" integer NOT NULL,
	"failed_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "metric_definition_versions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"metric_definition_id" uuid NOT NULL,
	"version" integer NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text,
	"definition" jsonb NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "metric_definitions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"current_version_id" uuid,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitors" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"metric_id" uuid NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text,
	"scope" jsonb,
	"condition" jsonb NOT NULL,
	"window" varchar(16) NOT NULL,
	"hold_for" varchar(16) NOT NULL,
	"workflow_id" varchar(128),
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" varchar(64) NOT NULL,
	"name" varchar(64) NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "organizations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "project_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"name" varchar(128) NOT NULL,
	"key" varchar(64) NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp (3) with time zone,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"name" varchar(128) NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metric_definition_versions" ADD CONSTRAINT "metric_definition_versions_metric_definition_id_metric_definitions_id_fk" FOREIGN KEY ("metric_definition_id") REFERENCES "public"."metric_definitions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metric_definitions" ADD CONSTRAINT "metric_definitions_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metric_definitions" ADD CONSTRAINT "metric_definitions_current_version_id_metric_definition_versions_id_fk" FOREIGN KEY ("current_version_id") REFERENCES "public"."metric_definition_versions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monitors" ADD CONSTRAINT "monitors_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monitors" ADD CONSTRAINT "monitors_metric_id_metric_definitions_id_fk" FOREIGN KEY ("metric_id") REFERENCES "public"."metric_definitions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_keys" ADD CONSTRAINT "project_keys_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "dirty_buckets_metric_idx" ON "dirty_buckets" USING btree ("metric_id","metric_version");--> statement-breakpoint
CREATE INDEX "metric_buckets_series_idx" ON "metric_buckets" USING btree ("metric_id","metric_version","dim_name","dim_value","granularity","bucket_start");--> statement-breakpoint
CREATE INDEX "metric_buckets_breakdown_idx" ON "metric_buckets" USING btree ("metric_id","metric_version","granularity","bucket_start","dim_name");--> statement-breakpoint
CREATE INDEX "events_project_id_name_timestamp_idx" ON "events" USING btree ("project_id","name","timestamp");--> statement-breakpoint
CREATE UNIQUE INDEX "metric_definition_versions_metric_id_version_idx" ON "metric_definition_versions" USING btree ("metric_definition_id","version");--> statement-breakpoint
CREATE INDEX "metric_definitions_project_id_idx" ON "metric_definitions" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "monitors_project_id_idx" ON "monitors" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "project_keys_key_idx" ON "project_keys" USING btree ("key");--> statement-breakpoint
CREATE INDEX "project_keys_project_id_idx" ON "project_keys" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "projects_organization_id_idx" ON "projects" USING btree ("organization_id");